name: "hikari"
description: "Fluid, responsive blog theme for Jekyll"

author: "William Beard"

url: "http://wbeard.github.io/wbeard"
baseurl: "http://wbeard.github.io/wbeard"

markdown: rdiscount
permalink: :year/:month/:title.html
pygments: true

# Google Analytics
ga_domain: m3xm.github.io
ga_tracking_id: UA-47727049-1
