name: "Perfect Code"
description: "Fluid, responsive blog theme for Jekyll"

author: "William Beard"

url: "http://wbeard.github.io/"
baseurl: "http://wbeard.github.io/wbeard"

markdown: rdiscount
permalink: :year/:month/:title.html
pygments: true

# Google Analytics
ga_domain: #
ga_tracking_id: #
